# DeathCompass Configuration

# Localization language
Language: en-US

# Enabled Worlds
EnabledWorlds:
  - world
  - another_world

# Destroy compass on drop
DestroyOnDrop: true

# Use UUID instead of player name
UseUUID: true

# Storage type ( file | sqlite )
StorageType: sqlite

# Time interval (in minutes) to sync file to disk (for StorageType file only)
FileSyncInterval: 5
