name: ${project.name}
version: ${project.version}
author: ${project.author}
main: com.winterhaven_mc.deathcompass.DeathCompassMain

commands:
   deathcompass:
      description: show DeathCompass settings or reload configuration file
      usage: /deathcompass help [command]
      permission: deathcompass.admin
      permission-message: You don't have the required deathcompass.admin permission.

permissions:
    deathcompass.use:
        description: Give player a compass on death and set compass target to last death location
        default: true
        
    deathcompass.reload:
        description: Reload DeathCompass config file
        default: op

    deathcompass.status:
        description: View DeathCompass settings
        default: op

    deathcompass.admin:
        description: DeathCompass admin commands
        default: op
        children:
            deathcompass.status: true
            deathcompass.reload: true        